In [2]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd  # 데이터 분석을 위한 라이브러리
import numpy as np   # 넘파이 : 숫자 계산

# 워닝 끄기
import warnings
warnings.filterwarnings('ignore')

In [15]:
games = pd.read_csv('리뷰.csv')
#games.gameid.values

array(['DJMAX', 'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX',
       'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX',
       'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX',
       'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX',
       'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX',
       'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX',
       'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX',
       'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX',
       'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX',
       'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX',
       'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX',
       'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX',
       'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX',
       'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX', 'DJMAX',
       'Ready_or_Not

In [7]:
from sentence_transformers import SentenceTransformer
corpus = games['review'].values.tolist() # 리뷰 임베딩

model = SentenceTransformer('jhgan/ko-sroberta-multitask')

embeddings = model.encode(corpus)# 리뷰 데이터 전부 인코딩 (센텐스 버트 모델)

embeddings[:5]
#임베딩 = 정규화(컴퓨터가 알아먹게끔)

array([[ 0.35382712, -0.5697627 , -0.21683566, ..., -0.49454522,
        -0.35012427,  0.5360391 ],
       [-0.4420631 ,  0.32140914, -0.00313227, ...,  0.5397908 ,
        -0.28604984, -0.00709499],
       [-0.5415595 , -0.05684227,  0.488865  , ...,  0.32799715,
        -0.33207694, -0.32564157],
       [-0.67893726,  0.06479859, -0.0687719 , ..., -0.22632687,
        -0.5452238 , -0.28211895],
       [-0.80998045,  0.28364825,  0.33774677, ...,  0.7681231 ,
        -0.25370428,  0.01956286]], dtype=float32)

In [8]:
from sklearn.metrics.pairwise import cosine_similarity
games_sim = cosine_similarity(embeddings, embeddings)

print(games_sim.shape)
print(games_sim[:10])

(980, 980)
[[1.         0.10800683 0.0985382  ... 0.167777   0.03557057 0.22814618]
 [0.10800683 0.99999976 0.43296713 ... 0.32089633 0.04334245 0.51185054]
 [0.0985382  0.43296713 0.99999994 ... 0.28710467 0.11666649 0.44637764]
 ...
 [0.19027707 0.37445286 0.35754517 ... 0.2104921  0.13525693 0.40033573]
 [0.22512957 0.38611576 0.38668388 ... 0.38860506 0.17831825 0.48484442]
 [0.19021267 0.44435927 0.3353199  ... 0.42150977 0.11894795 0.47040704]]


In [21]:
games_sim_sorted_ind = games_sim.argsort()[:, ::-1] # ::-1 : 역순으로 정렬
print(games_sim_sorted_ind[:5])

[[  0 897 238 ... 924 428  69]
 [  1  19 227 ... 326 590 379]
 [  2  19  44 ... 730 327 482]
 [  3 485 724 ... 601 589 715]
 [  4  48  90 ... 730 717 449]]


In [22]:
title_movie = games[games['gameid'] == 'ELDEN_RING']
title_movie

gameid                                             review  \
487  ELDEN_RING                                           피했다고 씨발아   
488  ELDEN_RING                          이 너머 점프 유효하다 이 앞 거짓말쟁이 있다   
489  ELDEN_RING  장점은 갓겜 단점은 개적화 제어판에서 쉐이더 캐쉬 무제한 설정 관리 프로그램 설정 ...   
490  ELDEN_RING  제발 에서는 중국서버 잠구는게 좋다 생각합니다 핵쓰고 선빵치고 아래 가르키며 약올리...   
491  ELDEN_RING                   트리가드 얘때문에 빡종하고 롤키니깐 헤카림 나와서 롤도 끔   
..          ...                                                ...   
582  ELDEN_RING  판 포팅 담당한 새끼 누구냐 주소까라 시간 반 진행했습니다 미리 응니컴 시전할까봐 ...   
583  ELDEN_RING                다른 개적화는 봐줄만 한데 년에 게임 지원 안되는건 너무 하네요   
584  ELDEN_RING                      진짜 너무재밌는데 내가 중옵따리로 할라고 산건 아닌데   
585  ELDEN_RING  완전무결한 게임은 아니지만 장점이 단점을 충분히 압도한다 프롬은 게임의 핵심이 최적...   
586  ELDEN_RING                                         어려워서 재미있네요   

     steam_purchase  
487            True  
488            True  
489            True  
490            True  
491            True  
..              ...  
582            True  
583            True  
584            True  
585            True  
586            True  

[100 rows x 3 columns]

In [23]:
title_index = title_movie.index.values
title_index

array([487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499,
       500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512,
       513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525,
       526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538,
       539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551,
       552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564,
       565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577,
       578, 579, 580, 581, 582, 583, 584, 585, 586], dtype=int64)

In [25]:
similar_indexes = games_sim_sorted_ind[title_index, :10]
similar_indexes

array([[487, 917, 947, 820, 921, 242, 200, 933, 888, 285],
       [488, 494, 936, 950, 272, 506, 453, 944, 469, 533],
       [489, 522, 136, 582, 786, 594, 498,   9,  25, 401],
       [490,  98, 331, 182, 979, 320, 350, 977, 322, 960],
       [491, 573, 947, 353, 365, 818, 979, 320, 506,  23],
       [492, 572, 573, 232, 539, 517, 933,  77,  50, 491],
       [493, 533, 547, 521, 948, 893, 652, 914, 955, 944],
       [494, 488, 950, 936, 506, 944, 106, 180, 818, 652],
       [495, 126, 232, 882, 250, 285, 432, 376,  17, 439],
       [496, 910, 634, 483, 165, 178, 122, 602, 242, 462],
       [497, 506, 975, 718, 421, 768, 549, 108, 885, 898],
       [498, 528, 522, 555, 568, 576,  73, 801, 783, 596],
       [499, 421, 885, 964, 506, 720, 766, 224, 705, 510],
       [500,  19, 131,  18,   8, 750, 657, 396,  81, 720],
       [501, 542, 554, 875, 476, 285, 200, 486, 773, 428],
       [502, 442, 627, 403, 540, 420, 443, 130, 278, 636],
       [503, 893, 620, 697, 561, 887, 549, 582, 220, 543

In [26]:
similar_indexes = similar_indexes.reshape(-1)
print(similar_indexes)

[487 917 947 820 921 242 200 933 888 285 488 494 936 950 272 506 453 944
 469 533 489 522 136 582 786 594 498   9  25 401 490  98 331 182 979 320
 350 977 322 960 491 573 947 353 365 818 979 320 506  23 492 572 573 232
 539 517 933  77  50 491 493 533 547 521 948 893 652 914 955 944 494 488
 950 936 506 944 106 180 818 652 495 126 232 882 250 285 432 376  17 439
 496 910 634 483 165 178 122 602 242 462 497 506 975 718 421 768 549 108
 885 898 498 528 522 555 568 576  73 801 783 596 499 421 885 964 506 720
 766 224 705 510 500  19 131  18   8 750 657 396  81 720 501 542 554 875
 476 285 200 486 773 428 502 442 627 403 540 420 443 130 278 636 503 893
 620 697 561 887 549 582 220 543 504 152 621 340 162 944 101 365 491 598
 505 410  41 626 390 250 448 200 810 781 506 571 576 499 421 549 578 896
 690 510 507 581 470 753 578 511 576 208 385 536 508 516 453 893  20 572
 529 241 517 883 509 724 324 496 287 432 376 802 439 363 510 549 199 421
 964 571 658 235 543 620 511 218 208 385 507 199 97

In [28]:
games.iloc[similar_indexes]

gameid                                   review  steam_purchase
487       ELDEN_RING                                 피했다고 씨발아            True
917   DARK_SOULS_III                                 아니 피했다고요            True
947   DARK_SOULS_III  아 시발 굴렀다고 아 시발 패링했다고 아 시발 막았다고 아 시발 다깼네            True
820          FIFA_22                                       병신            True
921   DARK_SOULS_III                                       시발            True
..               ...                                      ...             ...
252  Devil_May_Cry_5                                  그냥 재미있엉            True
876          FIFA_22                                  재밌다 할만함            True
280  Devil_May_Cry_5                                 아주 재밌습니다            True
957   DARK_SOULS_III                             재밌다 화나면서 재밌다            True
958   DARK_SOULS_III                    조금밖에 안해봤지만 중독성있고 재밌네요            True

[1000 rows x 3 columns]

In [31]:
def find_sim_games_ver1(df, sorted_ind, title_name, top_n=5):
    
    # 인자로 입력된 movies_df DataFrame에서 'title' 컬럼이 입력된 title_name 값인 DataFrame추출
    title_games = df[df['gameid'] == title_name]
    
    # title_named을 가진 DataFrame의 index 객체를 ndarray로 반환하고 
    # sorted_ind 인자로 입력된 genre_sim_sorted_ind 객체에서 유사도 순으로 top_n 개의 index 추출
    title_index = title_games.index.values
    similar_indexes = sorted_ind[title_index, :(top_n)]
    
    # 추출된 top_n index들 출력. top_n index는 2차원 데이터 임.
    # dataframe에서 index로 사용하기 위해서 1차원 array로 변경
    print(similar_indexes)    
    # 2차원 데이터를 1차원으로 변환
    similar_indexes = similar_indexes.reshape(-1)
    
    return df.iloc[similar_indexes]

In [33]:
similar_games = find_sim_games_ver1(games, games_sim_sorted_ind, 'ELDEN_RING', 5)

similar_games[['gameid']].drop_duplicates()

[[487 917 947 820 921]
 [488 494 936 950 272]
 [489 522 136 582 786]
 [490  98 331 182 979]
 [491 573 947 353 365]
 [492 572 573 232 539]
 [493 533 547 521 948]
 [494 488 950 936 506]
 [495 126 232 882 250]
 [496 910 634 483 165]
 [497 506 975 718 421]
 [498 528 522 555 568]
 [499 421 885 964 506]
 [500  19 131  18   8]
 [501 542 554 875 476]
 [502 442 627 403 540]
 [503 893 620 697 561]
 [504 152 621 340 162]
 [505 410  41 626 390]
 [506 571 576 499 421]
 [507 581 470 753 578]
 [508 516 453 893  20]
 [509 724 324 496 287]
 [510 549 199 421 964]
 [511 218 208 385 507]
 [512 232 707 242 751]
 [513 538 519 543 547]
 [514 516  63 525 241]
 [515 165 657 598  41]
 [516 508 514 572 241]
 [517 539 572 933 713]
 [518 549 397 753 563]
 [519 536 679 513 429]
 [520 627 218 568 130]
 [521 547 533 493 556]
 [522 498 786 596  73]
 [523 255 418 399 457]
 [524 398 797 208 267]
 [525 514 241 947 652]
 [526 714 536 507 894]
 [527 837 159 395 860]
 [528  73 498 557 555]
 [529  82 374 394 447]
 [530 862 8

gameid
487            ELDEN_RING
917        DARK_SOULS_III
820               FIFA_22
272       Devil_May_Cry_5
136          Ready_or_Not
331            Longvinter
634  Monster_Hunter_World
483            God_of_War
718               Valheim
19                  DJMAX